apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-2-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/OmerSade1/mongo-openshift.git
    targetRevision: HEAD
    path: frutis
    helm:
      valueFiles:
        - values.yaml 
  destination:
    server: https://api.ocp.octopus.labs:6443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true