apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nodejs-app
spec:
  host: <your hostname in the managed-cluster>
  to:
    kind: Service
    name: nodejs-app
  port:
    targetPort: 3000
  tls:
    termination: edge